# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\" \n\x08\x43\x65ntroid\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"#\n\x05Range\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\",\n\x08Int_Data\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x13\n\x03val\x18\x02 \x01(\x0b\x32\x06.Point\"V\n\x13MasterMapperRequest\x12\x15\n\x05range\x18\x01 \x01(\x0b\x32\x06.Range\x12\x1c\n\tcentroids\x18\x02 \x03(\x0b\x32\t.Centroid\x12\n\n\x02id\x18\x03 \x01(\x05\"&\n\x14MasterMapperResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x14MasterReducerRequest\x12\x15\n\rnum_centroids\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\"\'\n\x15MasterReducerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"=\n\x14ReducerMapperRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\x12\x11\n\tmapper_id\x18\x02 \x01(\x05\"0\n\x15ReducerMapperResponse\x12\x17\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\t.Int_Data\"\x1d\n\x0f\x43\x65ntroidRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x10\x43\x65ntroidResponse\x12\x1c\n\tcentroids\x18\x01 \x03(\x0b\x32\t.Centroid2}\n\x06Mapper\x12\x37\n\x06RunMap\x12\x14.MasterMapperRequest\x1a\x15.MasterMapperResponse\"\x00\x12:\n\x07GetData\x12\x15.ReducerMapperRequest\x1a\x16.ReducerMapperResponse\"\x00\x32~\n\x07Reducer\x12<\n\tRunReduce\x12\x15.MasterReducerRequest\x1a\x16.MasterReducerResponse\"\x00\x12\x35\n\x0cGetCentroids\x12\x10.CentroidRequest\x1a\x11.CentroidResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CENTROID']._serialized_start=16
  _globals['_CENTROID']._serialized_end=48
  _globals['_RANGE']._serialized_start=50
  _globals['_RANGE']._serialized_end=85
  _globals['_POINT']._serialized_start=87
  _globals['_POINT']._serialized_end=116
  _globals['_INT_DATA']._serialized_start=118
  _globals['_INT_DATA']._serialized_end=162
  _globals['_MASTERMAPPERREQUEST']._serialized_start=164
  _globals['_MASTERMAPPERREQUEST']._serialized_end=250
  _globals['_MASTERMAPPERRESPONSE']._serialized_start=252
  _globals['_MASTERMAPPERRESPONSE']._serialized_end=290
  _globals['_MASTERREDUCERREQUEST']._serialized_start=292
  _globals['_MASTERREDUCERREQUEST']._serialized_end=349
  _globals['_MASTERREDUCERRESPONSE']._serialized_start=351
  _globals['_MASTERREDUCERRESPONSE']._serialized_end=390
  _globals['_REDUCERMAPPERREQUEST']._serialized_start=392
  _globals['_REDUCERMAPPERREQUEST']._serialized_end=453
  _globals['_REDUCERMAPPERRESPONSE']._serialized_start=455
  _globals['_REDUCERMAPPERRESPONSE']._serialized_end=503
  _globals['_CENTROIDREQUEST']._serialized_start=505
  _globals['_CENTROIDREQUEST']._serialized_end=534
  _globals['_CENTROIDRESPONSE']._serialized_start=536
  _globals['_CENTROIDRESPONSE']._serialized_end=584
  _globals['_MAPPER']._serialized_start=586
  _globals['_MAPPER']._serialized_end=711
  _globals['_REDUCER']._serialized_start=713
  _globals['_REDUCER']._serialized_end=839
# @@protoc_insertion_point(module_scope)
